name: Test lib

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.11.0-dev.3937+78eb3c561
    - run: zig build test
